name: hello world

on:
  push:
    branches:


jobs:
  hello_old:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: step 1
        run: cat readme
        shell: bash
        
  goodbye:
    runs-on: ubuntu-latest
    steps: 
      - name: step 2
        if: github.ref == 'test'
        run: echo "goog by from test"

  
